---
services:
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - swag:/config
      - ./api.subfolder.conf:/config/nginx/proxy-confs/api.subfolder.conf
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Asia/Jerusalem
      - URL=encyclo-flower.com
      - SUBDOMAINS=dev
      - ONLY_SUBDOMAINS=true  # Will need to change for production
      - EMAIL=encyclo.flower@gmail.com
      - VALIDATION=http  # Required: certbot validation method
    ports:
      - 80:80
      - 443:443
    networks:
      - web
      - development
      - production

  # website:
  #   image: ohad24/encyclo-flower-website:latest
  #   container_name: website
  #   restart: always
  #   env_file:
  #     - website.env
  #   networks:
  #     - production

  # api:
  #   image: ohad24/encyclo-flower:latest
  #   container_name: api
  #   restart: always
  #   env_file:
  #     - api.env
  #   networks:
  #     - production

  # website-dev:
  #   image: ohad24/encyclo-flower-website:develop
  #   container_name: website-dev
  #   restart: always
  #   env_file:
  #     - website-dev.env
  #   networks:
  #     - development

  # api-dev:
  #   image: ohad24/encyclo-flower:develop
  #   container_name: api-dev
  #   restart: always
  #   env_file:
  #     - api-dev.env
  #   networks:
  #     - development

volumes:
  swag:

networks:
  web:
  development:
  production:
