version: "3.9"
services:
  swag:
    image: ohad24/encyclo-flower-swag:edge  # TODO: Switch to "latest"
    container_name: swag
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - swag:/config
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Asia/Jerusalem
      - URL=encyclo-flower.com
      - SUBDOMAINS=www,dev
      - ONLY_SUBDOMAINS=false
      - EMAIL=encyclo.flower@gmail.com
      - VALIDATION=http  # Required: certbot validation method
    ports:
      - 80:80
      - 443:443
    networks:
      - web
      - development
      - production

  api:
    image: ohad24/encyclo-flower-api:latest
    restart: always
    env_file:
      - PRODUCTION.env
    volumes:
      - ./google_cred.json:/app/google_cred.json
    networks:
      - production

  api-dev:
    image: ohad24/encyclo-flower-api:edge
    restart: always
    env_file:
      - DEVELOPMENT.env
    volumes:
      - ./google_cred.json:/app/google_cred.json
    networks:
      - development

volumes:
  swag:

networks:
  web:
  development:
  production:
