---
services:
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - swag:/config
      - ./api.subfolder.conf:/config/nginx/proxy-confs/api.subfolder.conf
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Asia/Jerusalem
      - URL=encyclo-flower.com
      - SUBDOMAINS=dev
      - ONLY_SUBDOMAINS=true  # Will need to change for production
      - EMAIL=encyclo.flower@gmail.com
      - VALIDATION=http  # Required: certbot validation method
    ports:
      - 80:80
      - 443:443
    networks:
      - web
      - development
      - production

  api:
    image: ohad24/encyclo-flower-api:latest
    restart: always
    env_file:
      # FIXME: api.env should have production variables, currently has test variables
      - api.env
    volumes:
      - ./google_cred.json:/app/google_cred.json
    networks:
      - production

  api-dev:
    image: ohad24/encyclo-flower-api:edge
    restart: always
    env_file:
      - api-dev.env
    volumes:
      - ./google_cred.json:/app/google_cred.json
    networks:
      - development

volumes:
  swag:

networks:
  web:
  development:
  production:
