version: "3.9"
services:
  swag:
    image: ohad24/encyclo-flower-swag:latest
    container_name: swag
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - swag-ssl:/config/etc/letsencrypt
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Asia/Jerusalem
      - URL=encyclo-flower.com
      - SUBDOMAINS=www,dev
      - ONLY_SUBDOMAINS=false
      - EMAIL=encyclo.flower@gmail.com
      - VALIDATION=http # Required: certbot validation method
    ports:
      - 80:80
      - 443:443
    networks:
      - web
      - development
      - production

  api:
    image: ohad24/encyclo-flower-api:latest
    restart: always
    env_file:
      - PRODUCTION.env
    volumes:
      - ./google_cred.json:/app/google_cred.json
    networks:
      - production

  api-dev:
    image: ohad24/encyclo-flower-api:edge
    restart: always
    env_file:
      - DEVELOPMENT.env
    volumes:
      - ./google_cred.json:/app/google_cred.json
    networks:
      - development

  frontend:
    image: ohad24/encyclo-flower-web:latest
    restart: always
    env_file:
      - PRODUCTION.env
    environment:
      - SERVER_BASE_URL=https://encyclo-flower.com/api/v1
    networks:
      - production

  frontend-dev:
    image: ohad24/encyclo-flower-web:edge
    restart: always
    env_file:
      - DEVELOPMENT.env
    environment:
      - SERVER_BASE_URL=https://dev.encyclo-flower.com/api/v1
    networks:
      - production

volumes:
  swag-ssl:

networks:
  web:
  development:
  production:
