---
- hosts: test
  become: True
  # gather_facts: False
  tasks:
    - name: Update packages
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: dist

    - name: Set hostname
      hostname:
        # NOTE: Manually change this to www for production
        name: srv01.encyclo-flower.com

    - name: Set timezone
      community.general.timezone:
        name: Asia/Jerusalem

    - name: Create group for the stack
      group:
        name: ef
        gid: 2000

    - name: Create user for the stack
      user:
        group: ef
        name: ef
        uid: 2000
      register: stack_user

    - name: Remove default ubuntu user
      user:
        name: ubuntu
        state: absent
        remove: yes

    - name: Harden ssh settings
      include_role: 
        name: ofersadan85.hardssh

    - name: Install pip & docker packages
      include_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - docker
          - docker-compose

    - name: Install docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_package_state: latest
        docker_install_compose: false
        docker_users: 
          - "{{ stack_user.name }}"

    - name: Install latest docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        mode: 0755

    - name: Ensure latest deployment files
      get_url: 
        url: "https://raw.githubusercontent.com/ohad24/encyclo-flower/main/server/{{ item }}"
        dest: "{{ stack_user.home }}/{{ item }}"
        owner: "{{ stack_user.name }}"
        group: "{{ stack_user.group }}"
        mode: 0440
      loop:
        - docker-compose.yml
        - deploy.sh
        - development.conf
        - production.conf

    - name: Ensure protected files permissions
      file:
        path: "{{ stack_user.home }}/{{ item }}"
        owner: "{{ stack_user.name }}"
        group: "{{ stack_user.group }}"
        mode: 0440
      loop:
        - .env
        - api.env
        - api-dev.env
        - website.env
        - website-dev.env
        - google_cred.json

    - name: Set up deployment key
      ansible.posix.authorized_key:
        user: "{{ stack_user.name }}"
        exclusive: yes
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMIotMW9zvh2p7JGMbankA6TK/TZUWq21dsTjUTfGDyX deployment@github
        key_options: 'command="sh ~/deploy.sh"'

    - name: Run docker services
      community.docker.docker_compose:
        project_src: "{{ stack_user.home }}"
        pull: yes
        remove_orphans: yes
